# Generated by Django 4.2.14 on 2024-08-22 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
