# Generated by Django 4.2.14 on 2024-08-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post1_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post1',
            name='image',
            field=models.ImageField(default='blog/Default.jpg', upload_to='blog/'),
        ),
    ]
