# Generated by Django 4.2.14 on 2024-09-15 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_date']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='subjcet',
            new_name='subject',
        ),
    ]
